bandada-infra/bandada

apps/api/src/app/common/utils.ts
apps/api/src/app/groups/dto/add-member.dto.ts
apps/api/src/app/groups/dto/update-group.dto.ts
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.spec.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.service.spec.ts
apps/api/src/app/invites/invites.service.ts

This PR makes some `GroupsService` functions and `groups` APIs faster by leveraging the cached groups saved in a JS map. Those groups are created with `@semaphore-protocol/group` in the service constructor, and create a Merkle tree for each DB group, that can be used to generate Merkle proofs. They can also be used by some functions, like `isGroupMember`, to avoid accessing data from the DB.
#41 
-   [ ] Yes
-   [x] No

Leveraging cached groups to make APIs more efficient

---

apps/api/src/app/accounts/account.service.ts
apps/api/src/app/accounts/entities/account.entity.ts
apps/api/src/app/common/utils.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.service.ts
apps/client/src/pages/permissioned-group.tsx
apps/client/src/types/invite.ts

This PR removes the `id` parameter from the entities which are shared externally with the APIs, since it is just used internally to manage DB entities. It also lets groups use the admin username rather than the admin id, and it hashes the admin `userId` parameter.
#54, #71
-   [ ] Yes
-   [x] No

Update some API entity parameters 

---

apps/api/src/app/groups/dto/create-group.dto.ts
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/groups.service.ts
apps/dashboard/src/components/create-group-modal.tsx

- Use same ID for off-chain groups in DB and Smart contract
- Set off-chain group limit to 100 in UI
#139 
-   [x] Yes
-   [ ] No
DB schema is changed. No migration is provided now.
Remove all tables and let TypeORM recreate the tables.

Unify groupId for off-chain groups

---

apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/dashboard/src/api/bandadaAPI.ts
apps/dashboard/src/components/navbar.tsx
apps/dashboard/src/context/auth-context.tsx
apps/dashboard/src/pages/groups.tsx
apps/dashboard/src/utils/session.ts

- Add API to add members manually
- Remove `/admin-groups` API and add `adminId` query param to `/groups`
- Update dashboard to new `/groups` to fetch admin groups
#195 
-   [ ] Yes
-   [x] No

API to add members manually & to get admin groups

---

.github/workflows/deploy.yml

Change role duration to 45', because workflow fails if deployment takes more than 30'

Change role duration to 2700"/45'

---

.github/scripts/deploy.sh

When ECR deployment takes more than 10', waiter **services-stable** that is responsible to confirm that the task in question enters a RUNNING state, fails with a **max attempts exceeded** error message.
It polls every 15" until a successful state has been reached and exits with a return code of 255 after 40 failed checks. It seems there is no way to adjust these thresholds, so the workaround is to add the aws cli command in a loop. The timeout was increased from 10' -> 20'. 
https://github.com/privacy-scaling-explorations/bandada/actions/runs/5678904600/job/15390041918
-   [ ] Yes
-   [x] No

Add Waiter services stable in a loop

---

apps/dashboard/src/components/new-group-stepper/general-info-step.tsx

The issue was with the validation of description input. I added a validation condition that disable "Continue" button until the description length is less than 10.
https://github.com/privacy-scaling-explorations/bandada/issues/274#issue-1854014987
-   [ ] Yes
-   [ ] No

feat: add validation for minimum description length

---

apps/api/src/app/groups/groups.controller.ts

Add the `x-api-key` parameter as required in `addMembers` in the API Docs.
Closes #309

Add the `x-api-key` parameter as required in the API Docs.

---

apps/api/src/app/credentials/credentials.service.test.ts
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/entities/member.entity.ts
apps/api/src/app/groups/groups.service.ts

This PR introduces a Many-to-Many relationship between Group and Member (a Group can contain multiple Members and a Member can join one or more Groups). The relationship is unidirectional and maintained in the Group. This allows for a join table between Group and Member that does not affect the current APIs, introducing an externally imperceptible (non-breaking) change. This approach was chosen because the join table did not require additional information beyond the Group and Member identifiers having a relationship, denoted by the term `Membership`.
- fix #265 
- complete https://github.com/privacy-scaling-explorations/bandada/pull/267
-   [ ] Yes
-   [x] No

Add Many-to-Many relationship between Group and Member

---

apps/api/src/app/credentials/credentials.service.test.ts

This PR adds a test case to the credential service to verify that the same credential (same OAuth account) can be associated with different identities at the same time, and that each of them can join a different group.
- Added missing test case
- Changed the provider from `twitter` to `github` as we are `GITHUB_FOLLOWERS` as credentials.
Closes #305 
-   [ ] Yes
-   [x] No
Depends on #325

Add a missing test case to check if the same credential with different identities can join different groups

---

apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/main.ts

See #303 
See #303 
-   [x] Yes
-   [ ] No
We are making a small alteration to the GroupService initialization process. Previously, we erroneously performed the `cachedGroups` initialization in the constructor. We have now introduced a dedicated method, `initialize()`, which must be called immediately after creating the GroupService object.

Wrong initialization of cached groups in Group service

---

apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/main.ts

See #303 
See #303 
-   [x] Yes
-   [ ] No
We are making a small alteration to the GroupService initialization process. Previously, we erroneously performed the `cachedGroups` initialization in the constructor. We have now introduced a dedicated method, `initialize()`, which must be called immediately after creating the GroupService object.

Re: Wrong initialization of cached groups in Group service

---

README.md
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.ts

minor typos

---

.github/scripts/build.sh
.github/scripts/deploy.sh
.github/workflows/deploy.yml
apps/client/.env.staging
apps/dashboard/.env.staging

- Enable staging deployment using deploy GH Actions workflow
- The production environment can only be deployed from the main branch
-   [ ] Yes
-   [x] No
- staging endpoints:
- staging.bandada.pse.dev
- api-staging.bandada.pse.dev
- client-staging.bandada.pse.dev

Enable ECS staging deployment 

---

README.md

This PR presents an updated version of the Bandada README, reflecting the latest developments and revised documentation.
-   [ ] Yes
-   [x] No

Update README to the latest version of Bandada

---

.github/workflows/deploy.yml

This PR introduces changes to the deploy workflow, in order to support auto deployment on the dev/stg environment when pushing to the dev branch.
-   [ ] Yes
-   [X] No
No

Support dev/stg auto deploy

---

apps/dashboard/src/pages/groups.tsx
apps/dashboard/src/types/Group.ts

Implementing a refactoring to list off-chain groups based on their creation date. This feature enhances the user experience by allowing users to easily access the most recently created groups.
this resolves issue #344 
Previously, users had to manually navigate through the list of groups to find the ones they were interested in because the groups were listed in alphabetical order.With this new re-factoring, the groups are displayed in order of their creation date, making it easier for users to find the latest content.
**No**

refactoring: lists the off-chain groups based on recent creation

---

libs/credentials/src/index.test.ts
libs/credentials/src/validators.ts
libs/credentials/src/validators/blockchainBalance/index.test.ts
libs/credentials/src/validators/blockchainBalance/index.ts
libs/credentials/src/validators/index.ts

This PR adds a new credential to check if a user has a balance greater than or equal to `minBalance`.
Closes #370 
-   [ ] Yes
-   [x] No

feat(credentials): add the blockchain balance validator

---

apps/api/src/app/credentials/credentials.service.test.ts
apps/api/src/app/credentials/credentials.service.ts
libs/credentials/src/validators/githubRepositoryCommits/index.ts

This PR:
- Solves this issue: #378
- Updates parameters in the `addMember` function in the credentials. More context [here](https://github.com/privacy-scaling-explorations/bandada/pull/371#discussion_r1477923532).
Closes #378
-   [ ] Yes
-   [x] No

Update the `GITHUB_REPOSITORY_COMMITS` validator

---

apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx

When creating a credential group in the dashboard, using the Github repository commits credential, there is a field to fill out called Repository where people should write the Github repository owner and name separated by a slash.
The idea is to add a placeholder in the Repository input box. The placeholder would be something like `<repo-owner>/<repo-name>`.
#385 
-   [ ] Yes
-   [x] No
With Changes:

feat: add placeholder to repository input

---

apps/dashboard/src/pages/group.tsx

If an off-chain group is credentials group then the ID and critieria is diplayed.This helps in easier management and accessibility/visibility.
This resolves #346 
Previously if a group was credential ,there was no mention of it anywhere,it would confuse the user and admin on the credential type(id) and the criteria.This feature Shows the credential id and criteria if it is a credential group.
No

feat: a feature that shows that displays the credential id and criteria of an off-chain group

---

libs/credentials/src/index.test.ts
libs/credentials/src/providers.ts
libs/credentials/src/providers/eas/index.ts
libs/credentials/src/providers/index.ts
libs/credentials/src/queryGraph.ts
libs/credentials/src/types/index.ts
libs/credentials/src/validateCredentials.ts
libs/credentials/src/validators.ts
libs/credentials/src/validators/easAttestations/index.test.ts
libs/credentials/src/validators/easAttestations/index.ts
libs/credentials/src/validators/index.ts

This PR integrates the Ethereum Attestation Service (EAS) provider with an `EAS_ATTESTATIONS` validator that takes `minAttestation` criteria for validation.
partially related to #355 
-   [ ] Yes
-   [x] No
This is the starting point for completing the #355

Add EAS provider with default `EAS_ATTESTATIONS` validator

---

apps/dashboard/src/components/add-member-modal.tsx

Previously, on-chain groups did not properly filter duplicate member IDs, allowing the same ID to be added multiple times without restriction. Now, when a user attempts to add an existing member ID to an on-chain group, an alert message  with the exact id/id's is displayed to notify the user and prevent the duplicate addition.
This resolves #302 
Alerting the user when a member id that is already present is added manually .
-Alert message with the exact duplicate id/id's is shown 
Additionally there was another bug that i came across while solving,the user can enter hexa values 
-it is saved in decimal format on the chain
-now another same hexa code can be added ,leads to duplicacy 
-Thus hexa checking is additionally added,it filters and converts to decimal and compares with the stored …

fix: prevent manual addition of duplicate member IDs in on-chain groups

---

.github/scripts/cloud-init.sh
.github/scripts/get_ip.sh
.github/scripts/run.sh
.github/workflows/ephemeral.yml

With this PR you can trigger a workflow that deploys bandada on an ephemeral EC2 instance. From the moment you launch the instance through to its (auto)termination, the uptime is 6h. Each user has the option to spawn only one running instance, regardless of the deployment branch; there is also the possibility to re-deploy a newer version. In this scenario the old instance is destroyed, and a new one is launched.
The instance' s IP address appears during the workflow execution, allowing access to bandada via a web browser and/or connecting to the instance via SSH. VPN access is required for both cases (to receive the SSH key, please DM me).
Please keep in mind that bandada deployment takes between 20-30' after workflow execution and the ephemeral instance specs consist of 2vCPUS, 8GB of …

Ephemeral runners for dev purposes

---

libs/credentials/src/types/index.ts
libs/credentials/src/validators/easAttestations/index.test.ts
libs/credentials/src/validators/easAttestations/index.ts

This PR adds the `recipient, attester, revocable, revoked, schemaId, isOffchain` options for the `EAS_ATTESTATIONS` credential validator enabling different and richer use-cases.
closes #401 
-   [ ] Yes
-   [x] No

Add options to `EAS_ATTESTATIONS` credential validator

---

apps/api/src/main.ts

The idea is to add the Bandada GitHub repository link to the API Docs: https://api.bandada.pse.dev/
I've added it on the top right of the page, just like in the Bandada Dashboard: https://bandada.pse.dev/
#403 
-   [ ] Yes
-   [X] No
Before:
After:
Note: I have only added a `customJsStr` attribute including the word "Github" and the hyperlink to the repository. Additionally, I've added the GitHub icon (just like in https://bandada.pse.dev/). To render the icon, it was tricky to use React components directly to the DOM using vanilla JavaScript. Therefore, I've create the icon using an inline SVG representation of the GitHub icon ("GitHub Octicons"). For future reference, it should be easier to change font-size, color, or any other attribute since everything is inside `customJsStr`

docs: add Bandada repository link to the API docs (closes #403)

---

apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx

When an error happened the user was getting 2 alerts, I removed the generic alert in the dashboard.
[404](https://github.com/privacy-scaling-explorations/bandada/issues/404)
-   [ ] Yes
-   [x] No

fix(final-preview-step.tsx): Removed the Uneccessary Alert the user was getting

---

apps/dashboard/src/pages/group.tsx

Created an `isGroupAdmin` var to hide the "Danger Zone" & "Use API Key" sections on the group page for non-admins. Also, refactored the "Add member" button to use this newly created var for hiding.
- #306
- #307
-   [ ] Yes
-   [x] No
|Before|After|
|--|--|
|![](https://github.com/privacy-scaling-explorations/bandada/assets/12480362/4efab62c-1f41-4305-9010-931ee096b479)|![](https://github.com/privacy-scaling-explorations/bandada/assets/12480362/c1d91e76-ff97-4d13-b320-35c8b85fcfa5)|

fix(dashboard): hide danger zone & api key sections for non-admins

---

apps/api/Dockerfile
apps/api/tsconfig.build.json
apps/client/Dockerfile
apps/client/package.json
apps/client/vite.config.ts
apps/dashboard/Dockerfile
libs/utils/package.json
libs/utils/tsconfig.build.json
yarn.lock

This PR improve build performance:
* container build time has improved by 4.5x (from 6m 31s down to 1m 31s)
* image size of api package has decreased by 6.8x (from 1.58 GB to 232 MB)
These improvements were achieved by:
* excluding unnecessary dependencies from other packages within this monorepo
* build only target package, rather than building unrelated packages in the monorepo
-   [ ] Yes
-   [x] No

build: improve build performance

---

apps/dashboard/src/pages/group.tsx

Hides the member edit actions from the UI for non-admins. Same method as used in #413.
- #415
-   [ ] Yes
-   [x] No
|Before|After|
|---|---|
|![](https://github.com/privacy-scaling-explorations/bandada/assets/12480362/fc73143c-cbe4-47b5-bf05-b8c5aa476d98)|![](https://github.com/privacy-scaling-explorations/bandada/assets/12480362/55044353-8ac4-41f8-bb4e-9c7a1a9b1b0c)|

fix(dashboard): hide member edit actions for non-admins

---

apps/dashboard/src/components/new-group-stepper/general-info-step.tsx

Disables continue button when checking if NaN on new group creation
closes #414
-   [ ] Yes
-   [x] No

feat(general-info-step.tsx): added check to disable continue when NaN

---

apps/api/src/app/credentials/credentials.controller.ts
apps/api/src/app/credentials/credentials.service.test.ts
apps/api/src/app/credentials/credentials.service.ts
apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx
libs/credentials/src/checkCriteria.ts
libs/credentials/src/types/index.ts
libs/credentials/src/validators/blockchainBalance/index.test.ts
libs/credentials/src/validators/blockchainBalance/index.ts
libs/credentials/src/validators/blockchainTransactions/index.test.ts
libs/credentials/src/validators/blockchainTransactions/index.ts
libs/credentials/src/validators/easAttestations/index.test.ts
libs/credentials/src/validators/easAttestations/index.ts
libs/credentials/src/validators/githubFollowers/index.ts
libs/credentials/src/validators/githubPersonalStars/index.ts
libs/credentials/src/validators/githubRepositoryCommits/index.ts
libs/credentials/src/validators/twitterFollowers/index.ts
libs/credentials/src/validators/twitterFollowingUser/index.ts

This PR moves the optional `context` field parameters (e.g., `blockNumber`, `attester`) from credential validators to be criterias.
Therefore, the dashboard has been updated to support this. Also, a new type (`boolean`) for criterias is now supported.
closes #411
-   [x] Yes
-   [ ] No
- To support optional parameters, this PR modifies the structure of the `criteriaABI' to accommodate properties with two fields: `type` (e.g. "number", "string", as before) and `optional`, a boolean to indicate whether the criteria is mandatory or not. 
- The `blockNumber` is removed from the `addMember()` credentials service as it is now provided by the user from the dashboard.

Make criterias from credentials validators context parameters

---

apps/api/.env.example
apps/api/src/app/credentials/credentials.service.test.ts
apps/api/src/app/credentials/credentials.service.ts
apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx
libs/utils/src/getSupportedNetworks.ts
libs/utils/src/types/index.ts

This PR:
- Adds Avalanche C-Chain Fuji as a supported network in the blockchain credential.
- Updates the `blockchainCredentialSupportedNetworks` variable type to make it easier to identify a network and display its name.
Closes #451
-   [x] Yes
-   [ ] No

Support Avalanche C-Chain Fuji in the blockchain credential

---

CONTRIBUTING.md
README.md
apps/api/src/main.ts
apps/client/src/pages/home.tsx
apps/contracts/contracts/README.md
apps/contracts/contracts/package.json
apps/dashboard/src/pages/home.tsx
apps/docs/docs/api/api-sdk.md
apps/docs/docusaurus.config.ts
apps/docs/static/data/articles.json
libs/api-sdk/README.md
libs/api-sdk/package.json
libs/credentials/README.md
libs/credentials/package.json
libs/hardhat/README.md
libs/hardhat/package.json
libs/utils/README.md
libs/utils/package.json
package.json

This PR updates the repo link across the codebase by replacing the old link `github.com/privacy-scaling-explorations/bandada` with the new link `github.com/bandada-infra/bandada`. The update is applied to all files and locations where the old repo link was referenced.
Closes #442 
-   [ ] Yes
-   [x] No

Update Repo Link

---

apps/dashboard/src/components/api-key.tsx

The issue is that the API Key component information was not being updated properly. 
Right now, when refreshing the API Key or the API Key is enabled or disabled, there are two requests to the backend: one to update admin info and the other to get the admin info. Since all the info to update is in the frontend, it shouldn't be necessary to send the second request. Since those functions won't be used frequently, this code can be refactored in another Pull Request.
#463 
-   [ ] Yes
-   [x] No

Fix API Key component not working properly

---

apps/api/src/app/groups/groups.service.ts
apps/client/src/pages/home.tsx
apps/client/src/utils/api.ts
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/invites.ts
libs/api-sdk/src/types/index.ts

- Fix `createGroup` and `createGroups` functions request. Now the right data object is sent in the `createGroups` request. 
- If the credentials parameter is undefined, it will be set to null in the server. 
- The group id is no longer part of the parameters to create a group, the group ids will be managed on the server.
- Update type names: Add clearer type names.
- Update Readme file to reflect the new changes in the Bandada API.
- Update some variable names and code refactoring.
Closes #466 
Closes #467
-   [x] Yes
-   [ ] No

Refactor API SDK

---

apps/dashboard/src/components/new-group-stepper/general-info-step.tsx
apps/dashboard/src/styles/components/tooltip.ts

Added a tooltip to display fingertip duration information, providing users with helpful insights into the duration of fingertip interactions.
Fixes #304 
No

added a  tooltip for fingertip duration for off-chain groups

---

apps/api/src/app/groups/docSchemas/groupResponse.ts
apps/api/src/app/groups/docSchemas/inviteResponse.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/groups/groups.utils.test.ts
apps/api/src/app/groups/groups.utils.ts
apps/api/src/app/invites/dto/create-invite.dto.ts
apps/api/src/app/invites/entities/invite.entity.ts
apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.module.ts
apps/api/src/app/invites/invites.service.test.ts
apps/api/src/app/invites/invites.service.ts
apps/api/src/app/utils/getAndCheckAdmin.ts
apps/api/src/app/utils/index.test.ts
apps/api/src/app/utils/index.ts
apps/client/src/pages/home.tsx
apps/dashboard/src/api/bandadaAPI.ts
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/invites.ts
libs/api-sdk/src/types/index.ts

This PR aims to add the `createInvite` endpoint to the APIs. This endpoint allows you to create a new `Invite` for a given `Group`. The `Invite` can only be created if you are an `Admin` of the given `Group` with an enabled and valid API key.
Specifically:
- Moved the `getAndCheckAdmin()` method from the group module utilities to the general `api` utilities.
- Updated the `Invites' entity fields in the `apiSDK` to reflect the correct entity.
- Added the `createInvite` endpoint and associated tests.
- Updated `client' and `dashboard' apps to reflect the changes.
closes #471 
-   [ ] Yes
-   [x] No

Add missing `createInvite` api endpoint

---

apps/api/src/app/groups/groups.controller.ts
libs/api-sdk/src/groups.ts

fix #482 
-   [ ] Yes
-   [x] No

Missing `return` statements for removeGroup(s) API SDK methods

---

libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts

This PR aims to fix the `BAD_RESPONSE` (500 - internal server error) caused by the wrong return statement.
-   [ ] Yes
-   [x] No

Avoid wrong `return` in removeGroup(s) API SDK methods

---

apps/api/src/app/groups/entities/group.entity.ts

The missing `cascade: ["remove"]` on Group entity for Invite entities was preventing the group to be deleted for the following error.
`QueryFailedError: update or delete on table "groups" violates foreign key constraint "invites_group_id_fkey" on table "invites"`
-   [ ] Yes
-   [x] No

Missing cascade remove for invites preventing deletion of groups

---

.yarn/patches/@semaphore-protocol-data-npm-3.10.0-48e6c0f59e.patch
apps/dashboard/package.json
yarn.lock

This PR aims to patch @semaphore-protocol/data so that `getGroups` in dashboard will return results sorted by creation time in descending method
https://github.com/bandada-infra/bandada/issues/433
-   [ ] Yes
-   [x] No

refactor: patch @semaphore-protocol/data to return result sorted by timestamp

---

apps/docs/docusaurus.config.ts

This PR updates the Algolia search values to use the correct ones for Bandada. 
Closes #506
-   [ ] Yes
-   [x] No

Update algolia values

---

README.md
apps/client/.env.production
apps/client/.env.staging
apps/dashboard/.env.production
apps/dashboard/.env.staging
apps/dashboard/src/components/navbar.tsx
apps/docs/docusaurus.config.ts

The dashboard url will be `app.bandada.pse.dev` instead of `bandada.pse.dev` in production and `app-staging.bandada.pse.dev` instead of `staging.bandada.pse.dev` in staging.
Closes #520
-   [x] Yes
-   [ ] No

chore: update dashboard url

---

apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts

Added new api-sdk features that allows users to get groups based on adminId and memberId.
Closes #493
Move PR #519 from `dev` branch to `main` branch
-   [ ] Yes
-   [x] No
Changed `where` from `array` to `object` so that it will return results for `AND` instead of `OR` when both `adminId` and `memberId` is present in the query.

feat(api,api-sdk): add getGroupsByAdminId() and getGroupsByMemberId()

---

apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/types/index.ts

This PR adds a new api-sdk function that allows users to generate a custom URL to join a credential group. 
This function takes in `baseUrl`, `groupId`, `commitment`, `providerName`, and an optional `redirectUri` as params and has 2 different returned URL, with and without `redirectUri`. Example:
With:
```ts
`${baseUrl}/credentials?group=${groupId}&member=${commitment}&provider=${providerName}&redirect_uri=${redirectUri}/groups?redirect=true`
```
Without:
```ts
`${baseUrl}/credentials?group=${groupId}&member=${commitment}&provider=${providerName}`
```
Closes #513 
-   [ ] Yes
-   [x] No

feat(api-sdk): add joinCredentialGroup()

---

libs/credentials/src/validators/blockchainBalance/index.test.ts
libs/credentials/src/validators/blockchainBalance/index.ts

The balance returned by the jsonRpcProvider is Wei and it should be converted to Ethers so that people can work with Ethers instead of Wei.
Closes #532
-   [ ] Yes
-   [x] No

Fix validate function in blockchain balance validator

---

README.md

This PR adds the Bandada board and Good First Issues links to the Readme file.
Closes #547
-   [ ] Yes
-   [x] No

docs: add bandada board and good first issues links to the readme file

---

apps/dashboard/src/pages/group.tsx

Added a box and button to the off-chain group page (/groups/off-chain/[]) to allow downloading of group information.
Change apps/dashborad/src/pages/group.tsx
- Added Download group box component
- added handleDownload function
- imported Spaser from chakura-ui
-   [ ] Yes
-   [✔︎] No

#395: Implement off-chain group information download

---

apps/api/.env.example
libs/utils/src/getSupportedNetworks.ts

polygon mumbai has been deprecated, and this change updates the network to polygon amoy.
#534
-   [ ] Yes
-   [x] No

 replace deprecated polygon mumbai with polygon amoy  #534

---

apps/website/next.config.mjs

When people access the hackathon-guide page, they will be redirected to the notion page which contains the information.
-   [ ] Yes
-   [x] No

chore(website): add hackathon guide redirect

---

apps/api/src/app/groups/docSchemas/group.ts
apps/api/src/app/groups/dto/create-group.dto.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/types/index.ts
package.json

This PR:
- Fixes the `getGroups()` function in the API SDK.
- A try catch was added to add `null` to the credentials that are not a valid JSON string.
- Updates the group credentials type in the API docs from object to string.
- Updates the default value for a credential group from `{}` to `'{"id":"BLOCKCHAIN_BALANCE","criteria":{"minBalance":"10","network":"Sepolia"}}'`.
- Improves developer experience when creating a credential groups programmatically.
- Adds support for multiple credentials groups.
- Adds a new script to run tests for a specific library: `yarn test:library <package-name>`.
Closes #561
-   [ ] Yes
-   [x] No

fix(api-sdk): fix get groups function

---

apps/api/package.json
apps/client/package.json
apps/contracts/contracts/package.json
apps/dashboard/package.json
apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/package.json
libs/credentials/package.json
libs/hardhat/package.json
libs/utils/package.json
yarn.lock

This PR adds code examples to create credential and multiple credentials groups to the `api-sdk` Readme file and the docs.
Closes #563
-   [ ] Yes
-   [x] No

docs: add credential groups to readme and docs

---

libs/credentials/README.md

This PR adds more examples of using the `validateCredentials` and `validateManyCredentials`
Issue #567 
-   [ ] Yes
-   [x] No

Update readme to add more examples of validateCredentials and validateManyCredentials

---

libs/credentials/README.md
libs/credentials/src/index.test.ts
libs/credentials/src/queryGraph.ts
libs/credentials/src/types/index.ts
libs/credentials/src/validators/easAttestations/index.test.ts
libs/credentials/src/validators/easAttestations/index.ts

This PR fixes a bug where the `queryGraph` function does not return the `request` function as intended.
This PR also has a code refactor that introduces a breaking change at validate `easAttestation`.
Specifically, validate `easAttestation` context no longer takes in `queryGraph` but `network` and `address` instead.
Example (Old):
```ts
validateCredentials(
{
...criteria
},
{
queryGraph: () => queryGraph
}
)
```
Example (New):
```ts
validateCredentials(
{
...criteria
},
{
network: EASNetworks.ETHEREUM,
address: "0x"
}
)
```
#568
-   [x] Yes
-   [ ] No
Please refer to the examples given above to migrate from the old easAttestation context to the new easAttestation context.

Improve and fix libs-credentials

---

libs/credentials/README.md

This PR updates the credential library readme file to reflect the changes made in EAS criteria.
-   [ ] Yes
-   [x] No

docs(libs-credentials): update credentials doc to reflect EAS criteria changes

---

libs/utils/src/index.ts

This PR fixes the missing util export that prevents users from using the new easCredentialSupportedNetwork.
-   [ ] Yes
-   [x] No

Fix missing util export

---

apps/api/src/app/credentials/credentials.service.ts
apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx
apps/dashboard/src/pages/credentials.tsx
libs/utils/src/index.ts

This PR implements a new feature to the the credentials API for easAttestations, introduced by PR #569.
This PR also implements the said API for Dashboard.
The URL structure to join a group is:
```console
http://localhost:3001/credentials?group=<group-id>&member=<member-commitment>&provider=eas&redirect_uri=<redirect-url>
```
Closes #573
-   [ ] Yes
-   [x] No

Add EAS Attestation credentials to API and Dashboard

---

libs/api-sdk/src/index.test.ts

Removed the global `let apiSdk: ApiSdk` and made it local for every test scenerio to make the tests more atomic.
Resolves https://github.com/bandada-infra/bandada/issues/583
-   [ ] Yes
-   [x] No

Remove global apiSdk variable in test and make it a local constant

---

apps/dashboard/src/pages/new-group.tsx

This PR fixes the bug of back button not working when creating on-chain group in dashboard.
Closes #585 
-   [ ] Yes
-   [x] No

Fix create on-chain group back button

---

apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts

This PR introduces a new feature that allows users to create associated group by using api-sdk.
Example:
```ts
const onchainGroupId = "1"
const apiKey = "70f07d0d-6aa2-4fe1-b4b9-06c271a641dc"
const associatedGroup = await apiSdk.createAssociatedGroup(onchainGroupId, apiKey)
```
-   [ ] Yes
-   [x] No

Add create associated group to api-sdk

---

apps/api/src/app/invites/dto/redeem-invite.dto.ts
apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.service.test.ts
apps/api/src/app/invites/invites.service.ts
apps/client/src/api/bandadaAPI.ts
apps/client/src/pages/home.tsx
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/invites.ts

This PR introduces a new features that allows users to redeem invite via API SDK. This API SDK can used after joining an on-chain group via invite link to mark the invite code as redeemed.
This new feature has been added to client app to showcase the functionality.
Discussed at https://github.com/bandada-infra/bandada/pull/584#discussion_r1824269818
-   [ ] Yes
-   [x] No

feat: redeemInvite API SDK

---

apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.service.test.ts
apps/api/src/app/invites/invites.service.ts
apps/client/src/api/bandadaAPI.ts
apps/client/src/pages/home.tsx
apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/invites.ts

This PR introduces a new feature that allows developers to check the validity of the invite code.
Example usage:
```ts
const inviteCode = "C5VAG4HD"
const groupId = "10402173435763029700781503965100"
const isValid = await apiSdk.checkInvite(inviteCode, groupId)
```
-   [ ] Yes
-   [x] No

feat: invite code validity check

---

apps/docs/docs/faq.md

This pull request fixes a typo in the FAQ section of the documentation. The original phrase:
**"The most frequent asked questions will be listed below."**
has been corrected to:
**"The most frequently asked questions will be listed below."**
The word "frequent" was incorrectly used as an adjective, when it should have been the adverb "frequently" to modify the verb "asked." 
This correction is important for grammatical accuracy and clarity. The phrase now follows the proper grammatical structure, ensuring the documentation is professional and easy to understand.
-   [ ] Yes
-   [x] No

Typo Update faq.md

---

apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts

This PR introduces a new API SDK that allows users to generate a link to join multiple credentials group.
Issue #606 
-   [ ] Yes
-   [x] No
Opted to add new API SDK method instead of updating the existing `getCredentialGroupJoinUrl` to prevent breaking change.

feat(api-sdk): add getMultipleCredentialsGroupJoinUrl

---

apps/client/src/pages/home.tsx

This pull request fixes an issue that occurs when a user joins a group via the invite link with an `inviteCode` and clicks the `Credential group ID` input, the invite input gets cleared. And also vice versa.
Fix: [#270](https://github.com/bandada-infra/bandada/issues/270)
-   [ ] Yes
-   [x] No

fix(client): disable input when user joins via an invite link

---

apps/client/src/pages/home.tsx
apps/client/src/utils/api.ts

This PR updates the current generate join url method in the Client app to use API SDK instead. 
This feature has been added for both credential group and multiple credentials group.
Issue #612 
-   [ ] Yes
-   [x] No

feat(client): use API SDK for credential group and multiple credentials group

---

apps/api/src/app/invites/dto/redeem-invite.dto.ts
apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.service.test.ts
apps/api/src/app/invites/invites.service.ts
apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/invites.ts

This PR introduces a new feature for users to redeem their invitation code manually or with their api key.
This new feature is available at api and api-sdk.
(This feature was originally in PR #608 but was ported out so that it could be used earlier.)
-   [ ] Yes
-   [x] No
Sample usage:
API
```ts
await invitesService.redeemInviteWithApiKey(
invite.code,
groupId,
admin.apiKey
)
await invitesService.redeemInviteKeyManually(
invite.code,
groupId,
admin.id
)
```
API SDK
```ts
const groupId = "10402173435763029700781503965100"
const inviteCode = "C5VAG4HD"
const invite = await apiSdk.redeemInvite(inviteCode, groupId)
```

feat: redeem invite manually or with api key

---

apps/docs/docs/tutorials/api-sdk/groups.md
apps/docs/docs/tutorials/api-sdk/onchain-invites.md

This PR adds a new section to tutorial to guide users on how to add members to an on-chain group using invite codes.
-   [ ] Yes
-   [x] No

docs: on-chain invites

---

apps/client/package.json
apps/client/src/pages/home.tsx
libs/api-sdk/README.md
yarn.lock

This PR add support for Semaphore identities v4 in the Client app. 
Closes #612 
-   [x] Yes
-   [ ] No

Improve client app

---

apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx
apps/dashboard/src/pages/new-group.tsx

This PR fixes a bug where a user clicks on credentials then on multiple credentials, the credentials and expressions will not be saved to the multiple credentials group.
This PR also fixes a minor bug on undefined type when checking for group type.
-   [ ] Yes
-   [x] No

fix(dashboard): missing credentials and expressions under certain conditions

---

apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx

This PR introduces a new `Clear` button to clear the credentials and expressions inputs when creating a multiple credentials group at dashboard. 
This button allows users to clear the inputs at one click instead of clicking `Back` to go back a step just to clear the inputs.
Closes #630 
-   [ ] Yes
-   [x] No

feat: add clear button to clear multiple credentials input

---

apps/dashboard/src/pages/groups.tsx

re #557
Refactor the UX code to make the groups stack (My groups and All Credential Groups) responsive for small and medium screens.
Also refactors the search bar and add group button to fit them in small/medium screens
-   [ ] Yes
-   [x] No

refactor(groups.tsx): make groups responsive for small and medium screen

---

apps/dashboard/src/pages/group.tsx

re #558
Make the group page on dashboard responsive for small and medium screens.
Used chakra responsive properties to define base, md and lg behavior 
-   [ ] Yes
-   [x] No
For small screens
For medium and large screens

refactor: make group responsive

---

apps/dashboard/src/components/group-card.tsx
apps/dashboard/src/components/new-group-stepper/access-mode-step.tsx
apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx
apps/dashboard/src/components/new-group-stepper/general-info-step.tsx
apps/dashboard/src/components/new-group-stepper/group-size-step.tsx
apps/dashboard/src/components/new-group-stepper/stepper-nav.tsx
apps/dashboard/src/components/new-group-stepper/stepper-preview.tsx
apps/dashboard/src/pages/new-group.tsx

re #559
Make the new group creation process responsive for small and medium screens.
-   [ ] Yes
-   [x] No
For large screens
For small/medium screens

refactor: make new group responsive

---

apps/dashboard/src/components/navbar.tsx

re #641
Make the connected account button responsive for small screens to prevent overlapping with bandada logo
-   [ ] Yes
-   [x] No
Small screens
Medium/large screens

refactor: make connected account button responsive for small sreens

---

libs/utils/package.json

The `bugs.url` field in the JSON configuration contains an unnecessary `.git` in the URL.
This has been corrected to point to the proper issues page:  
```json
"bugs": {
"url": "https://github.com/bandada-infra/bandada/issues"
}
```  
-   [ ] Yes
-   [x] No
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

fix: Fix incorrect URL in bugs.url field

---

apps/api/src/app/groups/dto/add-member-to-groups.dto.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/docs/docs/api-sdk.md
libs/api-sdk/README.md
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts

This PR introduces 2 new features to API and API SDK which allows users to:
- Get groups with multiple group ids.
- Add member to multiple groups.
API
```http
GET http://localhost:3000/groups?groupIds={groupId}&groupIds={groupId}
```
```ts
const groupIds = ["1", "2"]
const groups = await this.groupsService.getGroups(groupIds)
```
API SDK
```ts
const groupIds = ["1", "2"]
const groups = await apiSdk.getGroupsByGroupIds(groupIds)
```
API
```http
POST http://localhost:3000/groups/member/{memberId}
```
```ts
const memberId = "memberId"
const groupIds = ["1", "2"]
const adminId = "adminId"
const apiKey = "apiKey"
const manual = await this.groupsService.addMemberToGroupsManually(groupIds, memberId, adminId)
const api = await this.groupsService.addMemberToGroupsWithApiKey(groupIds, memberId, …
```

feat: add getGroupsByGroupIds and addMemberToGroups
