.env.sample
.gitignore
apps/api/Dockerfile
docker-compose.override.yml
docker-compose.yml

Add docker container for api.
Closes #3 
-   [ ] Yes
-   [x] No

feat(infra): setup docker tooling

---

apps/api/src/app/app.module.ts
apps/api/src/app/members/dto/add-member.dto.ts
apps/api/src/app/members/entities/member.entity.ts
apps/api/src/app/members/members.controller.spec.ts
apps/api/src/app/members/members.controller.ts
apps/api/src/app/members/members.module.ts
apps/api/src/app/members/members.service.spec.ts
apps/api/src/app/members/members.service.ts
apps/api/src/main.ts
package.json
yarn.lock

- Add basic functions of the members API(getMembers, addMember)
- Add unit tests for the API
- Get members list: Get /api/members/:groupName
- Get member by index: Get /api/members/:groupName/:index (index for new added member will be [max index of the list + 1])
- Add member: Post /api/members/:groupName <- Body { identityCommitment: "..."}
- Add unit tests for the API
As there is no DB at the moment, I just made it with fake list
More functions and test will be added after the Groups API and DB tasks are completed
#4
-   [ ] Yes
-   [x] No

Members API

---

apps/api/src/app/groups/dto/create-group.dto.ts
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.spec.ts
apps/api/src/app/groups/groups.service.ts
apps/dashboard/src/hooks/useGroups.ts

Add api to get admin's groups data that is used to admin Dashboard.
-   [ ] Yes
-   [x] No

Get admin's groups data api for admin Dashboard

---

.env.example
apps/api/src/app/accounts/account.module.ts
apps/api/src/app/accounts/account.service.ts
apps/api/src/app/accounts/entities/account.entity.ts
apps/api/src/app/app.module.ts
apps/api/src/app/auth/auth.service.ts
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.spec.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/entities/invite.entity.ts
apps/api/src/app/invites/invites.service.spec.ts
apps/api/src/app/invites/invites.service.ts
package.json
yarn.lock

This PR replace MongoDB with SQLite. SQLite is serverless, self-contained and doesn't need any configuration. It should be a good choice for our first beta version.
The default DB file path is `dist/data/zk-groups.db`. [`sqlitebrowser`](https://sqlitebrowser.org/dl/) is a good and open-source SQLite browser.
#38 
-   [ ] Yes
-   [x] No

SQLite support

---

apps/api/src/app/groups/groups.service.spec.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.service.spec.ts
apps/api/src/app/invites/invites.service.ts

This PR update the service error messages with the same format.
#40 
-   [ ] Yes
-   [x] No

Common pattern for API errors

---

apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.service.spec.ts
apps/api/src/app/invites/invites.service.ts

Refactoring error handling with invite code

---

apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/group-box/group-card.tsx
apps/dashboard/src/hooks/useOnchainGroups.ts
apps/dashboard/src/pages/manage.tsx
libs/onchain/src/lib/Semaphore/onchainGroups.ts

Add onchain group addMember function
#52 
-   [ ] Yes
-   [x] No

feat: add onchain-group member logic(frontend)

---

apps/api/src/app/auth/auth.controller.ts
apps/dashboard/src/components/navbar.tsx
apps/dashboard/src/pages/my-groups.tsx

refactor: use cookies for http requests only

---

apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/create-group-modal.tsx
apps/dashboard/src/components/group-box/index.tsx
apps/dashboard/src/hooks/useOnchainGroups.ts
apps/dashboard/src/pages/manage.tsx
apps/dashboard/src/pages/my-groups.tsx

fix: add exception handler for group name parsing
fix: remove description field for on-chain groups
fix: fix formatting in about section of manage group page
fix: fix add member button text for on-chain group
#107 
-   [ ] Yes
-   [x] No

Minor fixes/refactor in dashboard

---

apps/api/src/app/auth/auth.controller.ts
apps/dashboard/src/components/group-box/index.tsx
apps/dashboard/src/components/navbar.tsx
apps/dashboard/src/hooks/useOnchainGroups.ts
apps/dashboard/src/pages/my-groups.tsx
apps/dashboard/src/pages/sso.tsx

Refactor how on-chain and off-chain auth is handled in the dashboard
#108 
-   [ ] Yes
-   [x] No

Refactor auth flow

---

apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/create-group-modal.tsx
apps/dashboard/src/pages/my-groups.tsx

Auto refresh group list upon creating a new group for off-chain groups.
Show message saying the delay in displaying newly added on-chain group.
Show success message when adding a new member to the on-chain group.
#109 
#110 
-   [ ] Yes
-   [x] No

Auto refresh group list upon creating a new group

---

apps/api/src/app/groups/groups.service.ts

This PR polishes the code to update the `ZKGroups` contract groups after 1 minute the group is updated. 
Closes #119 
-   [ ] Yes
-   [x] No

Refactoring on code to update zk-groups contract groups

---

README.md

Add running production mode to Readme
Add env variables to Readme
#129 
-   [ ] Yes
-   [x] No

chore: add env to readme

---

apps/api/Dockerfile
apps/api/src/app/invites/invites.controller.ts
apps/client/Dockerfile
apps/client/src/pages/permissioned-group.tsx
apps/client/src/types/invite.ts
apps/dashboard/Dockerfile
apps/dashboard/src/main.tsx
docker-compose.yml

- Add groupId in getInvite response
- Fix API port in Docker
- Remove unnecessary code
None
-   [ ] Yes
-   [x] No

Minor fixes/improvements

---

apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/group.utils.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/dto/create-invite.dto.ts
apps/api/src/app/invites/invites.service.test.ts
apps/api/src/app/invites/invites.service.ts
apps/client/src/hooks/usePermissionedGroups.ts
apps/client/src/pages/permissioned-group.tsx
apps/dashboard/src/app/app.tsx
apps/dashboard/src/components/create-group-modal.tsx
apps/dashboard/src/components/group-box/group-card.tsx
apps/dashboard/src/components/invite-modal.tsx
apps/dashboard/src/hooks/useInvites.ts
apps/dashboard/src/hooks/useMembers.ts
apps/dashboard/src/hooks/useOnchainGroups.ts
apps/dashboard/src/pages/manage.tsx
apps/dashboard/src/types/groups/index.ts

Refactor routes to use groupId instead of groupName
None
-   [x] Yes
-   [ ] No
Change in DB schema

Refactor routes to use groupId instead of groupName

---

.dockerignore
apps/api/Dockerfile
apps/client/Dockerfile
apps/dashboard/Dockerfile

Fix docker config to work with yarn workspace
#138 
-   [ ] Yes
-   [x] No

Fix docker config to work with yarn workspace

---

.eslintrc.json
apps/client/src/app.tsx
apps/client/src/main.tsx
apps/client/src/pages/home.tsx
apps/client/src/pages/permissioned-group.tsx
apps/dashboard/src/app.tsx
apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/create-group-modal.tsx
apps/dashboard/src/components/group-box/group-card.tsx
apps/dashboard/src/components/navbar.tsx
apps/dashboard/src/components/sso-button.tsx
apps/dashboard/src/main.tsx
apps/dashboard/src/pages/home.tsx
apps/dashboard/src/pages/manage.tsx
apps/dashboard/src/pages/my-groups.tsx
package.json

This PR fixes the remaining ESLint issues mostly related to React components.
None
-   [ ] Yes
-   [x] No

Fixed remaining ESLint errors

---

apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.service.test.ts

Update off-chain group fingerprint without delay
#151 
-   [ ] Yes
-   [x] No

Update off-chain group fingerprint without delay

---

apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/dashboard/src/api/zkGroupsAPI.ts
apps/dashboard/src/pages/manage.tsx

Add remove members functionality for off-chain groups
#78 
-   [ ] Yes
-   [x] No

Add remove members functionality for off-chain groups

---

apps/api/.env.example
apps/api/.env.production
apps/api/package.json
apps/api/src/app/app.module.ts
apps/api/src/app/auth/strategies/github.strategy.ts
apps/api/src/app/auth/strategies/reddit.strategy.ts
apps/api/src/app/auth/strategies/twitter.strategy.ts
apps/api/src/app/groups/groups.service.ts
apps/client/.env.local
apps/client/.env.production
apps/client/package.json
apps/contracts/contracts/package.json
apps/contracts/package.json
apps/dashboard/.env.local
apps/dashboard/.env.production
apps/dashboard/package.json
apps/dashboard/src/api/semaphoreAPI.ts
libs/hardhat/package.json
yarn.lock

This PR separates the secret env variables from the other ones, which can be part of the git repo. Each app (expect `contracts`) includes three env files:
* `.env.example`: it must be copied to an `.env` file (ignored by Git) and contains the secret env variables necessary to run the app
* `.env.local`: it contains the env variables to be used in a developer environment
* `.env.production`: it contains the env variables to be used in a production environment
This PR also updates the Semaphore dependencies.
-   [ ] Yes
-   [x] No

Separation of env secret variables

---

.github/scripts/build.sh
.github/scripts/deploy.sh
.github/workflows/deploy.yml
README.md
appspec.yml
docker-compose.prod.yml
scripts/after_install.sh
scripts/start_app.sh
scripts/stop_app.sh
scripts/validate_app.sh

Rename to Bandada in AWS scripts
#165 
-   [ ] Yes
-   [x] No

Rename to Bandada in AWS scripts

---

apps/dashboard/src/pages/my-groups.tsx

Fix NewGroup button disabled for off-chain auth
#177 
-   [ ] Yes
-   [x] No

Fix NewGroup button disabled for off-chain auth

---

apps/api/package.json
apps/api/src/app/groups/entities/group.entity.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/groups/groups.utils.ts
apps/dashboard/src/api/bandadaAPI.ts
apps/dashboard/src/pages/manage.tsx
database/seed.sql
yarn.lock

- Implement API to configure API access for groups
- Implement API to add members via API
- Implement API to remove members via API
- Implement UI in dashboard for admins to manage API access
#50 
-   [ ] Yes
-   [x] No

Implement API Access

---

apps/api/src/app/groups/dto/update-group.dto.ts
apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/groups/groups.utils.ts

Add API for Reputation Criteria
#190 
-   [ ] Yes
-   [x] No

Add API for Reputation Criteria

---

libs/reputation/README.md
libs/reputation/src/index.ts
libs/reputation/src/validators.ts
libs/reputation/src/validators/githubFollowers/index.test.ts
libs/reputation/src/validators/githubPersonalStars/index.test.ts
libs/reputation/src/validators/githubRepositoryCommits/index.test.ts
libs/reputation/src/validators/index.ts
libs/reputation/src/validators/twitterFollowers/index.test.ts
libs/reputation/src/validators/twitterFollowingUser/index.test.ts
libs/reputation/src/validators/twitterFollowingUser/index.ts

Closes #208
-   [ ] Yes
-   [x] No

New Twitter validator for users who follow other specific users

---

libs/utils/src/getProvider.ts

Add provider url for localhost

---

apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts

Update fingerprint when tree depth is changed

---

database/seed.sql

Update SQL Seed file

---

database/seed.sql

Fix foreign key constraint in seed file

Fix foreign key constraint

---

apps/api/package.json
apps/api/src/app/app.module.ts
apps/api/src/app/groups/dto/update-group.dto.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/invites/invites.controller.ts
apps/api/src/app/invites/invites.service.ts
apps/dashboard/src/api/bandadaAPI.ts
apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/create-group-modal.tsx
apps/dashboard/src/pages/group.tsx
apps/dashboard/src/utils/shortenNumber.ts
yarn.lock

This PR adds a mechanism to prevent spamming using some APIs and solves some UI/backend bugs.
Closes #232, #239, #236
-   [ ] Yes
-   [x] No

Small improvements and bug fixes

---

apps/api/package.json
package.json
yarn.lock

Change swagger location

---

apps/api/src/app/groups/groups.controller.ts

Update API Docs in Add Member function

---

docker-compose.yml

Uncomment postgres from docker compose
#248 
-   [ ] Yes
-   [x] No

Uncomment postgres from docker compose

---

apps/api/src/app/groups/docSchemas/groupResponse.ts
apps/api/src/app/groups/docSchemas/index.ts
apps/api/src/app/groups/docSchemas/inviteResponse.ts
apps/api/src/app/invites/invites.controller.ts
libs/api-sdk/src/config.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/index.test.ts
libs/api-sdk/src/index.ts
libs/api-sdk/src/invites.ts
libs/api-sdk/src/types/index.ts

Add invites in API SDK

---

README.md
apps/client/.env.production
apps/contracts/contracts/README.md
apps/dashboard/.env.production
libs/api-sdk/README.md
libs/api-sdk/src/config.ts
libs/hardhat/README.md
libs/reputation/README.md
libs/utils/README.md

Update production domain

---

apps/api/package.json
apps/client/package.json
apps/client/src/pages/home.tsx
apps/client/src/utils/api.ts
apps/contracts/contracts/package.json
apps/dashboard/package.json
apps/dashboard/src/hooks/use-session-data.ts
libs/api-sdk/package.json
libs/api-sdk/src/apiSdk.ts
libs/api-sdk/src/groups.ts
libs/api-sdk/src/invites.ts
libs/api-sdk/src/types/index.ts
libs/credentials/package.json
libs/hardhat/package.json
libs/utils/package.json
yarn.lock

This PR fixes some minor bugs of the api-sdk lib and adds it to the client app.
Closes #260
-   [ ] Yes
-   [x] No

API lib to the client app

---

apps/dashboard/src/components/navbar.tsx

Adding link to "https://bandada.pse.dev" to the Heading
Closes https://github.com/privacy-scaling-explorations/bandada/issues/273
-   [ ] Yes
-   [x] No

Adding link to "https://bandada.pse.dev" to the Heading

---

README.md

docs: minor fix typo "beck-end"

---

CONTRIBUTING.md
README.md
libs/credentials/README.md

fix: typos
-   [ ] Yes
-   [x] No

fix: typos

---

libs/utils/README.md

Add info to the readme file of the utils library

---

apps/dashboard/src/components/group-card.tsx
apps/dashboard/src/components/new-group-stepper/general-info-step.tsx

Fix UI bugs when creating on-chain groups

---

apps/dashboard/src/components/add-member-modal.tsx
apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx

fix #294
-   [ ] Yes
-   [x] No

refactor: better Error Messages

---

libs/api-sdk/src/apiSdk.ts

Change the type of the config parameter to any in the constructor in the api-sdk

---

apps/api/src/app/groups/groups.service.test.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/main.ts

Revert Merge pull request #330 from privacy-scaling-explorations/fix/cached-groups"
This reverts commit e9bd9dad0a5346f3c2727479e35267c13c237c84, reversing changes made to 2e36b6d188a39aaaf4275343a3d60ffec3fe48b6.

Revert Merge pull request #330

---

apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx

Closes #335 
-   [ ] Yes
-   [x] No

Improve ux when creating a group

---

apps/api/src/app/groups/groups.service.ts

Closes #303 
-   [ ] Yes
-   [x] No

Fix init cached groups

---

apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.ts

Sync branches

---

apps/dashboard/src/main.tsx
apps/dashboard/src/pages/group.tsx

fix #279
Add a Chakra Toast to send a confirmation when successfully adding a new member to a group
-   [ ] Yes
-   [x] No

feat: success Message when adding member

---

.github/scripts/postgres.sh
.github/workflows/postgres.yml
database/seed.sql

With this PR, you can trigger a GitHub Actions workflow that invokes a lambda function to manipulate a postgres database.
-   [ ] Yes
-   [x] No
No

Postgres restore

---

apps/dashboard/src/pages/home.tsx

Previously, the groups, group, and new page had a gradient background. This commit changes the background color to pink for consistency and improved visibility.
This change resolves issue #345 
No

style: dashboard background colour change for selective pages

---

apps/api/src/app/groups/docSchemas/group.ts
apps/api/src/app/groups/groups.controller.ts
apps/api/src/app/groups/groups.service.ts
apps/api/src/app/groups/groups.utils.test.ts
apps/api/src/app/groups/groups.utils.ts
libs/api-sdk/src/types/index.ts

Returning group/groups fingerprint in APIs/SDK response
This closes #285
-   [ ] Yes
-   [x] No

feat: returning group/groups fingerprint in APIs/SDK response

---

libs/api-sdk/src/types/index.ts

376
Add Bandada API url to the supported urls enum.
#376 
-   [ ] Yes
-   [x] No

Feat: add staging url

---

apps/dashboard/src/api/bandadaAPI.ts

Updates parameters in the`addMemberByCredentials` request in the dashboard. More context [here]( https://github.com/privacy-scaling-explorations/bandada/pull/371#discussion_r1477923532).

refactor(dashboard): update correct parameter order

---

apps/api/src/app/credentials/credentials.service.ts
apps/dashboard/src/pages/credentials.tsx

Closes #417
-   [ ] Yes
-   [x] No

Update code comments

---

apps/contracts/contracts/README.md
libs/api-sdk/README.md
libs/credentials/README.md
libs/hardhat/README.md
libs/utils/README.md

Fix broken links (https://github.com/privacy-scaling-explorations/bandada/issues/421)

Fix broken links

---

libs/api-sdk/src/apiSdk.ts

Removed axios config example

---

apps/dashboard/src/utils/session.ts

add try catch for `JSON.parse` to prevent from breaking,  if stored data is not valid
N/A
-   [ ] Yes
-   [X] No

refactor(dashboard): add try for JSON.parse to prevent breaking

---

.github/workflows/release.yml

re #447
-   [ ] Yes
-   [x] No

Update release workflow to fix automatic release notes

---

libs/api-sdk/src/groups.ts

This PR adds the correct parameters to the data object in the request.
Closes #469
-   [ ] Yes
-   [x] No

API SDK: Use the correct data object in the request

---

libs/api-sdk/src/groups.ts
libs/api-sdk/src/invites.ts
libs/api-sdk/src/types/index.ts

This PR fixes some small minor issues on the `api-sdk` package.
fix #478 
fix #479 
fix #480 
-   [ ] Yes
-   [x] No

Fix minor issues on API SDK

---

apps/docs/docs/api-sdk.md
apps/docs/docs/api.md
apps/docs/docs/api/_category_.json
apps/docs/docs/api/api-docs.md
apps/docs/docs/api/api-sdk.md
apps/docs/docs/faq.md
apps/docs/docs/intro.md
apps/docs/docs/resources.mdx
libs/api-sdk/README.md

This PR updates API SDK Readme file and docs with the latest Bandada changes. 
Closes #474
-   [ ] Yes
-   [x] No

docs: update api sdk docs with the latest bandada changes

---

.github/workflows/coverall.yml
libs/api-sdk/src/index.test.ts

Now the API SDK has 100% test coverage.
The coverall github workflow should finish successfully.
Re #458
-   [ ] Yes
-   [x] No

Add tests to the API SDK

---

.github/workflows/release.yml
README.md

This PR updates the release github workflow to publish packages automatically. 
Closes #450 
-   [ ] Yes
-   [x] No

Update release workflow to publish packages automatically

---

.github/workflows/release.yml
README.md
apps/api/package.json
apps/client/package.json
apps/contracts/contracts/package.json
apps/dashboard/package.json
libs/api-sdk/package.json
libs/credentials/package.json
libs/hardhat/package.json
libs/utils/package.json
yarn.lock

Fix release github workflow

---

.github/scripts/cloud-init.sh

Fix GH URL for ephemeral runners.
-   [ ] Yes
-   [X] No

Fix broken GH URL

---

apps/docs/static/data/videos.json

This PR updates the video resources.
Closes #508
Closes #499
-   [ ] Yes
-   [x] No

Update video resources

---

libs/api-sdk/package.json

Update `api-sdk` module to support `Node16`, `NodeNext`, and `Bundler` in `tsconfig` `ModuleResolution`.
fix #498 
-   [ ] Yes
-   [x] No

fix(api-sdk): update api-sdk module to support more `ModuleResolution`

---

apps/website/app/layout.tsx
apps/website/common/settings.ts

This PR adds updates to the website:
- Dashboard url 
- Open graph data
Re #522
-   [ ] Yes
-   [x] No

Update urls in the website

---

apps/website/shared/data/projects.ts

Fixed the incorrect hyperlinks.
Re #539 
-   [ ] Yes
-   [x] No
The links for `BrickWall` and `B-Hook` in the [discussion thread](https://github.com/orgs/bandada-infra/discussions/494#discussion-6588579) still needs to be updated.

Fix incorrect hyperlinks in apps/website Projects built using Bandada

---

apps/website/shared/data/events.ts

This PR adds the DIF hackathon event to the website.
-   [ ] Yes
-   [x] No

docs(website): update events

---

apps/website/shared/data/projects.ts

Adding two new projects to project list
-   [ ] Yes
-   [x] No

docs: joby and SHIELD Space added to project list

---

apps/website/shared/data/events.ts

This PR adds ETHIndia to the website.
-   [ ] Yes
-   [x] No

Add ETHIndia to the website

---

README.md
apps/client/src/pages/home.tsx

This PR improves the Client app header. 
Re #612
-   [ ] Yes
-   [x] No

Improve client app header

---

apps/docs/docs/api-sdk.md

docs: update redeem invite code block

---

apps/dashboard/src/pages/groups.tsx

added the numbers of groups for my groups and all credential groups on the group page
added the numbers of groups for my groups and all credential groups on the group page
Added the numbers of groups for my groups and all credential groups on the group page
#636
https://github.com/bandada-infra/bandada/issues/636
-   [ ] Yes
-   [ -] No
-   [ -] I have performed a self-review of my code
-   [- ] I have commented my code, particularly in hard-to-understand areas
-   [- ] My changes generate no new warnings
-   [- ] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [ -] I have added tests that prove my fix is effective or that my feature works
-   [- ] New and existing unit tests pass locally with my changes
> [!IMPORTANT]
> We do not accept minor grammatical fixes …

Fix issues #636

---

apps/dashboard/src/pages/groups.tsx

This PR makes the cards displayed in all credential groups section responsive. 
Closes #656
-   [ ] Yes
-   [x] No
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while appreciated, are not a priority for merging. If there is a grammatical error feel free …

refactor: make the cards displayed in all credential groups section responsive

---

apps/api/src/app/groups/groups.controller.ts

This PR checks if groupIds is string or array. 
Closes #669 
-   [ ] Yes
-   [x] No
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while appreciated, are not a priority for merging. If there is a grammatical error feel free to message the team.

fix: check groupids type
